services:
  postgresql_db:
    image: postgres:17.5
    container_name: postgresql_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_dw:/var/lib/postgresql/data
    networks:
      - my_network

  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter_lab
    ports:
      - "8888:8888"
    env_file:
      - .env
    # pasta local ./notebooks aparecerá como /home/jovyan/work no Jupyter
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      # defina no .env; use algo forte em produção
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: "1000"
      NB_GID: "1000"
      PYTHONPATH: /home/jovyan/work
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgresql_db
      POSTGRES_PORT: "5432"
    command: >
      bash -lc "
        pip install --no-cache-dir psycopg2-binary SQLAlchemy ipykernel &&
        start-notebook.py --NotebookApp.token=$${JUPYTER_TOKEN}
      "
    depends_on:
      - postgresql_db
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres_data_dw:
